[project_name]
data = 'ad_tensor'

[root_file]
usr = 'docs/user.xrst'
dev = 'docs/devel.xrst'

[heading]
#   level         0,     1,     2,     3,     4,
character = [   '#',   '*',   '=',   '-',   '.',  ]
overline  = [ false, false, false, false, false,  ]

[project_dictionary]
data = [
    # C++ keywords
    '''
    const
    ''',
    # abbreviations
    '''
    var
    vec
    ''',
]
